import requests

DATA : dict = {
    'article_id' : 10,
    'llm_used' : 'llama3.2',
    'generated_summary' : 'Lorem ipsum  vulputate in tellsto.Aenean mollis varius elit sed tempor. Vivamus sed tincidunt nunc. In pellentesque turpis convallis purus placerat egestas. Phasellus rutrum lorem in augue tempus tempus. In varius lacus at mi pharetra, eget aliquam nisl ultricies. Nam quis lobortis ante, eu gravida felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum mollis viverra quam, vitae porttitor purus dignissim non. Nullam eget ipsum sem. Aenean quis tellus a dui rhoncus condimentum a vel nisl. Cras sit amet mauris consequat, accumsan sapien sit amet, lobortis arcu. Etiam vel sem turpis. Maecenas viverra scelerisque dui non aliquet. Duis ipsum ante, porttitor eget erat et, iaculis dapibus lacus. Maecenas dictum dictum ipsum, et rutrum velit pharetra eget. Pellentesque sagittis vestibulum sapien id porta. Curabitur eu odio ultricies dolor lobortis placerat. Donec quis laoreet enim. Etiam tristique pulvinar dolor ut porta. Ut mattis odio at nisi euismod, vel consectetur nibh porta. Sed gravida mattis nunc, a congue felis pretium a. Duis consequat dui tincidunt velit vulputate, a sollicitudin arcu eleifend. Morbi lectus massa, malesuada in rhoncus sed, tempor eget ante. Aliquam et urna maximus, efficitur justo id, porta quam. Sed a leo feugiat, dictum massa maximus, ultricies ligula. Donec et augue est. In hac habitasse platea dictumst. Cras id dolor leo. Sed aliquam accumsan tincidunt. Etiam consectetur sit amet nisl id bibendum. Curabitur luctus vitae diam nec consectetur. Fusce ut pharetra ex, id rhoncus nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed vitae nisi finibus quam convallis ultrices quis quis enim. Curabitur aliquam mi vel pretium euismod. Pellentesque rutrum sodales quam eget lobortis. Morbi vel convallis ex. Nulla porta lacus eu congue consectetur. Ut congue dictum nisl, at vulputate ligula feugiat ut. Maecenas nec dapibus lorem. Vivamus posuere tortor vehicula hendrerit lobortis. In suscipit, lacus vel posuere varius, nisl justo facilisis diam, sit amet imperdiet enim nibh ac sapien. Nam massa metus, sollicitudin eu mollis et, malesuada placerat odio. Ut non lorem hendrerit, mollis tellus ut, posuere sapien. Aenean lacinia urna non lectus fringilla, sed bibendum elit congue. Phasellus eleifend, nisi et tincidunt commodo, ipsum sem scelerisque tortor, eu pulvinar ligula sapien a ante. Nulla facilisi. Nunc sed augue ultricies mi elementum congue ut nec enim. Nam suscipit dolor quis leo euismod molestie.'
}

requested = requests.post('http://127.0.0.1:9200/api/add/article-summary', json=DATA)
print(requested.status_code, requested.text)